"use client";
// ============================================================================
// VIEW LAYER — Teacher: Report, for ONE section at a time.
//
// Replaced a ComingSoonPage. Ordered by the question a teacher actually opens it
// with — "is this class in trouble, and who?" — so the answer is at the top and
// the evidence is below it:
//
//   tiles -> distribution -> who to chase -> which project -> what the pipeline says
//
// THE HEADLINE AVERAGE IS THE RECORDED GRADE, not the pipeline score. It is the
// number that reaches a report card, and the repository page already tells
// teachers the CI score is "not applied automatically". Pipeline figures still
// appear, per project and per stage, labelled as what they are.
//
// Everything here excludes fabricated demo runs — see the backend's
// DashboardsService.classReport. When any were dropped the page says so, because
// a teacher who pressed "Run pipeline" and saw nothing change deserves the
// reason rather than a number that silently ignored them.
// ============================================================================
import { useSession } from "@/viewmodels/useSession";
import {
  useClassReport,
  ATTENTION_LABELS,
  ATTENTION_IS_TEACHER_TASK,
} from "@/viewmodels/useClassReport";
import type {
  ClassReportGradeBand,
  ClassReportProject,
  ClassReportStage,
} from "@/models/types";
import {
  Avatar,
  Banner,
  Card,
  EmptyState,
  GenericPill,
  ProgressBar,
  Select,
  Skeleton,
  Stat,
  StateBoundary,
  SectionHeading,
  cn,
} from "@/components/ui";
import { PageHeader } from "@/components/domain/PageHeader";

export default function TeacherReportsPage() {
  const { user, selectedOrgId } = useSession();
  const vm = useClassReport(user?.id ?? null, selectedOrgId ?? null);

  return (
    <div className="space-y-6">
      <PageHeader
        // Teacher area: title at the right of the band. See PageHeader's titleAlign.
        titleAlign="end"
        title="Report"
        subtitle="How one section is doing — submissions, marks, and what the pipeline says."
        actions={
          vm.sections.length > 0 && (
            <Select
              aria-label="Section to report on"
              value={vm.selectedId ?? ""}
              onChange={(e) => vm.select(e.target.value)}
            >
              {vm.sections.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.label}
                </option>
              ))}
            </Select>
          )
        }
      />

      <StateBoundary
        isLoading={vm.isLoadingSections || vm.isLoading}
        error={vm.error}
        onRetry={vm.refetch}
        isEmpty={!vm.isLoadingSections && vm.sections.length === 0}
        emptyFallback={
          <EmptyState
            title="No sections in this laboratory"
            description="Your IT admin creates class sections. Once you run one here, its report appears on this page."
          />
        }
        loadingFallback={
          <div className="space-y-4">
            <Skeleton className="h-28 w-full rounded-xl" />
            <Skeleton className="h-64 w-full rounded-xl" />
          </div>
        }
      >
        {vm.data && (
          <div className="space-y-6">
            {/* A non-zero count means the demo button is still enabled somewhere
                that is being graded for real. Stated once, at the top, rather
                than repeated beside every pipeline figure it affected. */}
            {vm.data.pipelineHealth.simulatedRunsExcluded > 0 && (
              <Banner tone="warning" title="Simulated runs excluded">
                {vm.data.pipelineHealth.simulatedRunsExcluded}{" "}
                {vm.data.pipelineHealth.simulatedRunsExcluded === 1
                  ? "pipeline run was"
                  : "pipeline runs were"}{" "}
                generated by the demo &ldquo;Run pipeline&rdquo; button rather than
                by real CI. They are left out of every figure below, so nothing
                here is averaged against an invented score.
              </Banner>
            )}

            {/* ---------------------------------------------------------- */}
            {/* 1. Tiles                                                   */}
            {/* ---------------------------------------------------------- */}
            <Card className="p-5 animate-fade-up">
              <div className="grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-5">
                <Stat label="Students" value={vm.data.totals.students} />
                <Stat label="Projects" value={vm.data.totals.projects} />
                <Stat
                  label="Submitted"
                  value={vm.rates.submitted === null ? "—" : `${vm.rates.submitted}%`}
                  hint={`${vm.data.totals.submitted} of ${vm.data.totals.expectedSubmissions}`}
                />
                <Stat
                  label="Marked"
                  value={vm.rates.marked === null ? "—" : `${vm.rates.marked}%`}
                  // Of SUBMITTED, not of expected — see ClassReportVM.rates.
                  hint={`${vm.data.totals.marked} of ${vm.data.totals.submitted} submitted`}
                />
                <Stat
                  label="Class average"
                  value={
                    vm.data.totals.averageGrade === null
                      ? "—"
                      : `${vm.data.totals.averageGrade}%`
                  }
                  // Says WHAT the number is over. An average that silently
                  // covered only marked work is the kind a teacher quotes to a
                  // parent and then cannot reproduce.
                  hint="marked work only"
                  tone={
                    vm.data.totals.averageGrade !== null &&
                    vm.data.totals.averageGrade < 70
                      ? "warning"
                      : "default"
                  }
                />
              </div>
            </Card>

            <div className="grid items-start gap-6 xl:grid-cols-2">
              {/* -------------------------------------------------------- */}
              {/* 2. Grade distribution                                    */}
              {/* -------------------------------------------------------- */}
              <Card className="p-5 animate-fade-up">
                <SectionHeading
                  title="Grade distribution"
                  subtitle="Where the marked students actually sit."
                />
                <div className="mt-4">
                  {vm.data.gradeDistribution.every((b) => b.count === 0) ? (
                    <p className="text-sm text-[var(--text-muted)]">
                      Nothing is marked yet, so there is no distribution to show.
                    </p>
                  ) : (
                    <GradeHistogram bands={vm.data.gradeDistribution} />
                  )}
                </div>
              </Card>

              {/* -------------------------------------------------------- */}
              {/* 3. Needs attention                                       */}
              {/* -------------------------------------------------------- */}
              <Card className="p-5 animate-fade-up">
                <SectionHeading
                  title="Needs attention"
                  subtitle="Worst first. Everyone else is on Student progress."
                />
                <div className="mt-4">
                  {vm.data.attention.length === 0 ? (
                    <p className="text-sm text-[var(--text-muted)]">
                      Nobody is behind, unmarked, or failing. Nothing to chase.
                    </p>
                  ) : (
                    <ul className="divide-y divide-[var(--border-subtle)]">
                      {vm.data.attention.map((s) => (
                        <li
                          key={s.studentId}
                          className="flex flex-wrap items-center gap-3 py-3 first:pt-0 last:pb-0"
                        >
                          <Avatar name={s.fullName} color={s.avatarColor} size="sm" />
                          <div className="min-w-0 flex-1">
                            <p className="truncate text-sm font-medium text-[var(--text-strong)]">
                              {s.fullName}
                            </p>
                            <p className="text-xs text-[var(--text-muted)]">
                              {s.submitted}/{s.expected} submitted · {s.marked} marked
                              {s.averageGrade !== null && ` · avg ${s.averageGrade}%`}
                            </p>
                          </div>
                          <div className="flex flex-wrap gap-1.5">
                            {s.reasons.map((r) => (
                              <span
                                key={r}
                                className={cn(
                                  "rounded-full px-2 py-0.5 text-[11px] font-medium ring-1",
                                  // The teacher's OWN backlog is neutral, not
                                  // red: a teacher scanning for problems should
                                  // not be sent chasing a student who did
                                  // everything right and is waiting on them.
                                  ATTENTION_IS_TEACHER_TASK[r]
                                    ? "bg-slate-50 text-slate-600 ring-slate-200"
                                    : "bg-amber-50 text-amber-800 ring-amber-200",
                                )}
                              >
                                {ATTENTION_LABELS[r]}
                              </span>
                            ))}
                          </div>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              </Card>
            </div>

            {/* ---------------------------------------------------------- */}
            {/* 4. Per project                                             */}
            {/* ---------------------------------------------------------- */}
            <Card className="animate-fade-up overflow-hidden">
              <div className="p-5 pb-0">
                <SectionHeading
                  title="Projects"
                  subtitle="Where one project stalled rather than one student."
                />
              </div>
              {vm.data.projects.length === 0 ? (
                <p className="p-5 text-sm text-[var(--text-muted)]">
                  This section has no projects yet.
                </p>
              ) : (
                <ProjectTable projects={vm.data.projects} />
              )}
            </Card>

            <div className="grid items-start gap-6 xl:grid-cols-2">
              {/* -------------------------------------------------------- */}
              {/* 5. Stage breakdown                                       */}
              {/* -------------------------------------------------------- */}
              <Card className="p-5 animate-fade-up">
                <SectionHeading
                  title="Pipeline stages"
                  subtitle="Class average per stage, from the latest real run of each repository."
                />
                <div className="mt-4">
                  <StageBreakdown stages={vm.data.stages} />
                </div>
                {/* The teaching read, stated rather than left to be inferred. */}
                <p className="mt-4 text-xs text-[var(--text-muted)]">
                  High on public tests and low on hidden tests means the class is
                  writing code that satisfies the tests it can see. That is a
                  lesson-plan signal, not a marking one.
                </p>
              </Card>

              {/* -------------------------------------------------------- */}
              {/* 6 + 7. Quality and pipeline health                       */}
              {/* -------------------------------------------------------- */}
              <div className="space-y-6">
                <Card className="p-5 animate-fade-up">
                  <SectionHeading
                    title="Code quality"
                    subtitle="SonarCloud — 35% of the mark."
                  />
                  {vm.data.quality.measuredRepos === 0 ? (
                    <p className="mt-4 text-sm text-[var(--text-muted)]">
                      Nothing measured yet. This is <strong>not</strong> the same as
                      clean code — SonarCloud has not reported on any repository in
                      this section.
                    </p>
                  ) : (
                    <>
                      <div className="mt-4 grid grid-cols-2 gap-5 sm:grid-cols-3">
                        <Stat label="Bugs" value={vm.data.quality.bugs} />
                        <Stat
                          label="Vulnerabilities"
                          value={vm.data.quality.vulnerabilities}
                          tone={
                            vm.data.quality.vulnerabilities > 0 ? "warning" : "default"
                          }
                        />
                        <Stat label="Code smells" value={vm.data.quality.codeSmells} />
                        <Stat
                          label="Debt ratio"
                          value={
                            vm.data.quality.averageDebtRatio === null
                              ? "—"
                              : `${vm.data.quality.averageDebtRatio}%`
                          }
                        />
                        <Stat
                          label="Duplication"
                          value={
                            vm.data.quality.averageDuplication === null
                              ? "—"
                              : `${vm.data.quality.averageDuplication}%`
                          }
                        />
                        <Stat label="Lines analysed" value={vm.data.quality.ncloc} />
                      </div>
                      <p className="mt-4 text-xs text-[var(--text-muted)]">
                        Across {vm.data.quality.measuredRepos}{" "}
                        {vm.data.quality.measuredRepos === 1
                          ? "repository"
                          : "repositories"}{" "}
                        SonarCloud actually measured. Repositories it could not read
                        are excluded rather than counted as clean.
                      </p>
                    </>
                  )}
                </Card>

                <Card className="p-5 animate-fade-up">
                  <SectionHeading
                    title="Pipeline health"
                    subtitle="Latest real run of each repository."
                  />
                  <div className="mt-4 grid grid-cols-3 gap-5">
                    <Stat label="With runs" value={vm.data.pipelineHealth.reposWithRuns} />
                    <Stat
                      label="Passing"
                      value={vm.data.pipelineHealth.passed}
                      tone="success"
                    />
                    <Stat
                      label="Failing"
                      value={vm.data.pipelineHealth.failed}
                      tone={vm.data.pipelineHealth.failed > 0 ? "warning" : "default"}
                    />
                  </div>

                  {/* A CONFIGURATION fault, and labelled as one. Per-repo this
                      only appears on a page nobody opens until the grade is
                      already in — by which point quality went ungraded silently. */}
                  {vm.data.pipelineHealth.sonarErrors.length > 0 && (
                    <div className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3">
                      <p className="text-sm font-medium text-amber-900">
                        {vm.data.pipelineHealth.sonarErrors.length}{" "}
                        {vm.data.pipelineHealth.sonarErrors.length === 1
                          ? "repository has"
                          : "repositories have"}{" "}
                        no SonarCloud wiring
                      </p>
                      <p className="mt-0.5 text-xs text-amber-800">
                        Quality is 35% of the mark and is going unmeasured on these.
                        A setup problem, not a student one.
                      </p>
                      <ul className="mt-2 space-y-1">
                        {vm.data.pipelineHealth.sonarErrors.map((e) => (
                          <li key={e.repoId} className="text-xs text-amber-900">
                            <code className="font-mono">{e.repoName}</code> — {e.error}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </Card>
              </div>
            </div>
          </div>
        )}
      </StateBoundary>
    </div>
  );
}

/**
 * The distribution, as bars sized against the FULLEST band rather than the class
 * size.
 *
 * Against the class size, a well-spread class renders four stubs and the shape —
 * which is the entire point of showing a distribution rather than a mean —
 * disappears.
 */
function GradeHistogram({ bands }: { readonly bands: ClassReportGradeBand[] }) {
  const peak = Math.max(...bands.map((b) => b.count), 1);

  return (
    <ul className="space-y-2.5">
      {bands.map((band) => (
        <li key={band.label} className="flex items-center gap-3">
          <span className="w-16 shrink-0 text-xs tabular-nums text-[var(--text-muted)]">
            {band.label}
          </span>
          <div className="min-w-0 flex-1">
            <ProgressBar
              value={band.count}
              max={peak}
              // The failing band reads as a warning; the rest are neutral. A
              // histogram in one colour makes the teacher find the bad bar.
              tone={band.max <= 50 && band.count > 0 ? "warning" : "platform"}
            />
          </div>
          <span className="w-6 shrink-0 text-right text-sm font-medium tabular-nums text-[var(--text-strong)]">
            {band.count}
          </span>
        </li>
      ))}
    </ul>
  );
}

function StageBreakdown({ stages }: { readonly stages: ClassReportStage[] }) {
  const scored = stages.filter((s) => s.percent !== null);

  if (scored.length === 0) {
    return (
      <p className="text-sm text-[var(--text-muted)]">
        No real pipeline runs in this section yet, so there is nothing to break down.
      </p>
    );
  }

  return (
    <ul className="space-y-3">
      {stages.map((stage) => (
        <li key={stage.stage} className="flex items-center gap-3">
          <span className="w-28 shrink-0 text-xs font-medium text-[var(--text-muted)]">
            {STAGE_LABELS[stage.stage] ?? stage.stage}
          </span>
          <div className="min-w-0 flex-1">
            {stage.percent === null ? (
              // Never a 0% bar. SANDBOX carries no points — it is pass/fail —
              // and an empty bar would say the class failed a stage it cannot
              // score on.
              <p className="text-xs text-[var(--text-muted)]">
                {stage.checksCounted > 0 ? "Pass/fail — no points" : "No data"}
              </p>
            ) : (
              <ProgressBar
                value={stage.percent}
                tone={stage.percent < 60 ? "warning" : "success"}
              />
            )}
          </div>
          <span className="w-12 shrink-0 text-right text-sm font-medium tabular-nums text-[var(--text-strong)]">
            {stage.percent === null ? "—" : `${stage.percent}%`}
          </span>
        </li>
      ))}
    </ul>
  );
}

const STAGE_LABELS: Record<string, string> = {
  SANDBOX: "Sandbox",
  LINT: "Lint",
  QUALITY: "Quality",
  PUBLIC_TESTS: "Public tests",
  HIDDEN_TESTS: "Hidden tests",
  SCORING: "Scoring",
};

function ProjectTable({ projects }: { readonly projects: ClassReportProject[] }) {
  return (
    <div className="mt-4 overflow-x-auto">
      <table className="w-full min-w-[42rem] text-sm">
        <thead>
          <tr className="border-y border-[var(--border-subtle)] text-left text-xs uppercase tracking-wide text-[var(--text-muted)]">
            <th className="px-5 py-2 font-medium">Project</th>
            <th className="px-5 py-2 text-right font-medium">Submitted</th>
            <th className="px-5 py-2 text-right font-medium">Marked</th>
            <th className="px-5 py-2 text-right font-medium">Overdue</th>
            <th className="px-5 py-2 text-right font-medium">Avg grade</th>
            <th className="px-5 py-2 text-right font-medium">Avg CI</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-[var(--border-subtle)]">
          {projects.map((p) => (
            <tr key={p.assignmentId}>
              <td className="px-5 py-3">
                <p className="font-medium text-[var(--text-strong)]">{p.title}</p>
                <p className="mt-0.5 flex flex-wrap items-center gap-1.5 text-xs text-[var(--text-muted)]">
                  {p.isGroup && <GenericPill size="sm">Group</GenericPill>}
                  {/* An absent deadline is a real teaching choice — ongoing
                      practice, self-paced labs — so it is stated, not blank. */}
                  {p.dueDate
                    ? `Due ${new Date(p.dueDate).toLocaleDateString()}`
                    : "No deadline"}
                </p>
              </td>
              <td className="px-5 py-3 text-right tabular-nums">
                {p.submitted}/{p.expected}
              </td>
              <td className="px-5 py-3 text-right tabular-nums">{p.marked}</td>
              <td
                className={cn(
                  "px-5 py-3 text-right tabular-nums",
                  p.overdue > 0 && "font-semibold text-amber-700",
                )}
              >
                {p.overdue > 0 ? p.overdue : "—"}
              </td>
              <td className="px-5 py-3 text-right font-medium tabular-nums text-[var(--text-strong)]">
                {p.averageGrade === null ? "—" : `${p.averageGrade}%`}
              </td>
              {/* Muted next to the recorded grade, on purpose: it is evidence,
                  not the mark. The repository page says the same thing in words
                  ("Not applied automatically"). */}
              <td className="px-5 py-3 text-right tabular-nums text-[var(--text-muted)]">
                {p.averagePipelineScore === null ? "—" : `${p.averagePipelineScore}%`}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
